import type { MonitoringItem } from '../types/monitoringBarang';

/**
 * Dummy / mock data for development.
 * In production, this module would call the Laravel backend via Inertia or Axios.
 */
export const MOCK_DATA: MonitoringItem[] = [
  {
    id: '1',
    contractId: 'TRK-2024-001',
    shippingSession: 'SS-20240715-A',
    customerName: 'PT. Bara Energi Nusantara',
    itemName: 'Excavator CAT 320',
    itemType: 'Alat Berat',
    origin: 'Kapal MV Orion',
    destination: 'Tongkang TK-08',
    status: 'In Transit',
    lastUpdate: '2024-11-06T10:30:00+07:00',
    estimatedArrival: '2024-11-08T08:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Tongkang',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-CAT-320',
    currentLocation: 'Perairan Selat (Kapal ke Tongkang)',
    totalWeight: '22.5 Ton',
    model: 'Hydraulic Excavator',
    manufacturer: 'Caterpillar Inc.',
    finalDestination: 'Site Tambang A, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '09 Nov 2024', time: '06:30', pic: 'Andi Pratama', notes: 'Ship-to-ship transfer ke Tongkang' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '10 Nov 2024', time: '09:00', pic: 'Budi Santoso', notes: 'Pelayaran antar pulau' },
      { id: 'cp3', name: 'Port Handling', status: 'current', date: '11 Nov 2024', time: '14:20', pic: 'Feri', notes: 'Pemindahan unit ke area penumpukan' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending', date: '12 Nov 2024', notes: 'Logistik darat via Lowbed (estimasi)' },
    ],
    documents: [],
    reports: [],
    photos: [],
    activities: [
      { id: 'act1', time: '14:20', date: '11 Nov 2024', title: 'Cargo arrived at Barge', user: 'Budi Santoso', role: 'Staff' },
    ],
  },
  {
    id: '2',
    contractId: 'TRK-2024-002',
    shippingSession: 'SS-20240714-B',
    customerName: 'PT. Kaltim Prima Coal',
    itemName: 'Bulldozer D6R',
    itemType: 'Alat Berat',
    origin: 'Tongkang TK-05',
    destination: 'Pelabuhan Merak',
    status: 'Delivered',
    lastUpdate: '2024-11-06T08:00:00+07:00',
    estimatedArrival: '2024-11-06T08:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Site',
    totalCheckpoints: 4,
    completedCheckpoints: 4,
    itemCode: 'EQ-CAT-D6R',
    currentLocation: 'Site Tambang, sudah dibongkar',
    totalWeight: '18.4 Ton',
    model: 'Track-Type Tractor',
    manufacturer: 'Caterpillar Inc.',
    finalDestination: 'Site Tambang B, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '02 Nov 2024', time: '06:00', pic: 'Rudi' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '02 Nov 2024', time: '14:00', pic: 'Joko' },
      { id: 'cp3', name: 'Port Handling', status: 'completed', date: '03 Nov 2024', time: '09:00', pic: 'Sari' },
      { id: 'cp4', name: 'Site Delivery', status: 'completed', date: '06 Nov 2024', time: '08:00', pic: 'Eko' },
    ],
    documents: [],
    reports: [],
    photos: [],
    activities: [
      { id: 'act1', time: '08:00', date: '06 Nov 2024', title: 'Cargo arrived at Site', user: 'Eko', role: 'Staff' },
    ],
  },
  {
    id: '3',
    contractId: 'TRK-2024-003',
    shippingSession: 'SS-20240716-C',
    customerName: 'PT. Berau Coal',
    itemName: 'Dump Truck 777E',
    itemType: 'Alat Berat',
    origin: 'Pelabuhan Bakauheni',
    destination: 'Site Tambang A',
    status: 'In Transit',
    lastUpdate: '2024-11-03T09:15:00+07:00',
    estimatedArrival: '2024-11-09T12:00:00+07:00',
    createdBy: 'Supervisor Utama',
    currentCheckpoint: 'Pelabuhan',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-CAT-777E',
    currentLocation: 'Perairan Selat (Kapal ke Tongkang)',
    totalWeight: '22.5 Ton',
    model: 'Hydraulic Excavator',
    manufacturer: 'Caterpillar Inc.',
    finalDestination: 'Site Tambang A, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '09 Nov 2024', time: '06:30', pic: 'Andi Pratama', notes: 'Ship-to-ship transfer ke Tongkang' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '10 Nov 2024', time: '09:00', pic: 'Budi Santoso', notes: 'Pelayaran antar pulau' },
      { id: 'cp3', name: 'Port Handling', status: 'current', date: '11 Nov 2024', time: '14:20', pic: 'Feri', notes: 'Pemindahan unit ke area penumpukan' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending', notes: 'Logistik darat via Lowbed (estimasi 12 Nov 2024)' },
    ],
    documents: [],
    reports: [],
    photos: [],
    activities: [
      { id: 'act1', time: '14:20', date: '11 Nov 2024', title: 'Cargo arrived at Port', user: 'Feri', role: 'Staff' },
    ],
  },
  {
    id: '4',
    contractId: 'TRK-2024-004',
    shippingSession: 'SS-20240710-D',
    customerName: 'PT. Adaro Energy',
    itemName: 'Mobile Crane 50T',
    itemType: 'Alat Berat',
    origin: 'Kapal B',
    destination: 'Tongkang C',
    status: 'Delayed',
    lastUpdate: '2024-11-06T08:00:00+07:00',
    estimatedArrival: '2024-11-05T18:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Pelabuhan',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-XCMG-50T',
    currentLocation: 'Pelabuhan, menunggu proses lanjutan (delay cuaca)',
    totalWeight: '32 Ton',
    model: 'Mobile Crane 50 Ton',
    manufacturer: 'XCMG',
    finalDestination: 'Site Tambang C, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '01 Nov 2024', time: '05:30', pic: 'Doni' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '01 Nov 2024', time: '18:00', pic: 'Agus' },
      { id: 'cp3', name: 'Port Handling', status: 'current', date: '06 Nov 2024', time: '08:00', pic: 'Feri', notes: 'Delay karena cuaca buruk' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [],
    reports: [],
    photos: [],
    activities: [
      { id: 'act1', time: '08:00', date: '06 Nov 2024', title: 'Delay dilaporkan - cuaca buruk', user: 'Feri', role: 'Staff' },
    ],
  },
  {
    id: '5',
    contractId: 'TRK-2024-005',
    shippingSession: 'SS-20240711-E',
    customerName: 'PT. Bukit Asam',
    itemName: 'Wheel Loader 950H',
    itemType: 'Alat Berat',
    origin: 'Tongkang K',
    destination: 'Pelabuhan V',
    status: 'Pending',
    lastUpdate: '2024-11-07T08:00:00+07:00',
    estimatedArrival: '2024-11-10T10:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Mother Vessel',
    totalCheckpoints: 4,
    completedCheckpoints: 0,
    itemCode: 'EQ-CAT-950H',
    currentLocation: 'Menunggu jadwal pemuatan dari kapal',
    totalWeight: '16.9 Ton',
    model: 'Wheel Loader',
    manufacturer: 'Caterpillar Inc.',
    finalDestination: 'Site Tambang D, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'pending' },
      { id: 'cp2', name: 'Barge Transit', status: 'pending' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [],
    reports: [],
    photos: [],
    activities: [
      { id: 'act1', time: '08:00', date: '07 Nov 2024', title: 'Shipping session dibuat', user: 'Administrator', role: 'Admin' },
    ],
  },
  {
    id: '6',
    contractId: 'TRK-2024-006',
    shippingSession: 'SS-20240715-F',
    customerName: 'PT. Indo Tambang Raya',
    itemName: 'Motor Grader 140K',
    itemType: 'Alat Berat',
    origin: 'Pelabuhan X',
    destination: 'Site Tambang C',
    status: 'In Transit',
    lastUpdate: '2024-11-06T10:30:00+07:00',
    estimatedArrival: '2024-11-09T08:00:00+07:00',
    createdBy: 'Supervisor Utama',
    currentCheckpoint: 'Pelabuhan',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-CAT-140K',
    currentLocation: 'Perjalanan darat menuju Site Tambang C',
    totalWeight: '17.2 Ton',
    model: 'Motor Grader',
    manufacturer: 'Caterpillar Inc.',
    finalDestination: 'Site Tambang C, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '04 Nov 2024', time: '10:00', pic: 'Hadi' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '04 Nov 2024', time: '22:00', pic: 'Wawan' },
      { id: 'cp3', name: 'Port Handling', status: 'current', date: '06 Nov 2024', time: '10:30', pic: 'Siti' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [],
    reports: [],
    photos: [],
    activities: [
      { id: 'act1', time: '10:30', date: '06 Nov 2024', title: 'Cargo arrived at Port', user: 'Siti', role: 'Staff' },
    ],
  },
  {
    id: '7',
    contractId: 'TRK-2024-007',
    shippingSession: 'SS-20240718-G',
    customerName: 'PT. Timah Persada',
    itemName: 'Electronics Devices',
    itemType: 'Kargo Umum',
    origin: 'Kapal H',
    destination: 'Tongkang R',
    status: 'In Transit',
    lastUpdate: '2024-11-05T08:30:00+07:00',
    estimatedArrival: '2024-11-08T10:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Tongkang',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-ELC-007',
    currentLocation: 'Tongkang, menuju Pelabuhan tujuan',
    totalWeight: '4.2 Ton',
    model: '-',
    manufacturer: '-',
    finalDestination: 'Gudang Distribusi, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '03 Nov 2024', time: '07:00', pic: 'Rian' },
      { id: 'cp2', name: 'Barge Transit', status: 'current', date: '05 Nov 2024', time: '08:30', pic: 'Dedi' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '08:30', date: '05 Nov 2024', title: 'Cargo transit via Barge', user: 'Dedi', role: 'Staff' }],
  },
  {
    id: '8',
    contractId: 'TRK-2024-008',
    shippingSession: 'SS-20240719-H',
    customerName: 'PT. Sinar Mas Agro',
    itemName: 'Pharmaceutical Products',
    itemType: 'Kargo Khusus',
    origin: 'Tongkang V',
    destination: 'Pelabuhan I',
    status: 'Delivered',
    lastUpdate: '2024-11-06T10:45:00+07:00',
    estimatedArrival: '2024-11-06T10:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Site',
    totalCheckpoints: 4,
    completedCheckpoints: 4,
    itemCode: 'EQ-PHM-008',
    currentLocation: 'Sudah diterima di gudang tujuan',
    totalWeight: '2.8 Ton',
    model: '-',
    manufacturer: '-',
    finalDestination: 'Gudang Farmasi, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '04 Nov 2024', time: '06:00', pic: 'Nina' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '04 Nov 2024', time: '15:00', pic: 'Yusuf' },
      { id: 'cp3', name: 'Port Handling', status: 'completed', date: '05 Nov 2024', time: '09:00', pic: 'Lina' },
      { id: 'cp4', name: 'Site Delivery', status: 'completed', date: '06 Nov 2024', time: '10:45', pic: 'Tono' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '10:45', date: '06 Nov 2024', title: 'Cargo arrived at destination', user: 'Tono', role: 'Staff' }],
  },
  {
    id: '9',
    contractId: 'TRK-2024-009',
    shippingSession: 'SS-20240720-I',
    customerName: 'PT. Antam Tbk',
    itemName: 'Crawler Crane 80T',
    itemType: 'Alat Berat',
    origin: 'Kapal MV Delta',
    destination: 'Tongkang TK-11',
    status: 'In Transit',
    lastUpdate: '2024-11-06T09:00:00+07:00',
    estimatedArrival: '2024-11-09T10:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Tongkang',
    totalCheckpoints: 4,
    completedCheckpoints: 1,
    itemCode: 'EQ-CRW-80T',
    currentLocation: 'Perairan, dalam perjalanan ke Tongkang',
    totalWeight: '48 Ton',
    model: 'Crawler Crane 80 Ton',
    manufacturer: 'Sumitomo',
    finalDestination: 'Site Tambang E, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '05 Nov 2024', time: '07:30', pic: 'Herman' },
      { id: 'cp2', name: 'Barge Transit', status: 'current', date: '06 Nov 2024', time: '09:00', pic: 'Wahyu' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '09:00', date: '06 Nov 2024', title: 'Cargo transit via Barge', user: 'Wahyu', role: 'Staff' }],
  },
  {
    id: '10',
    contractId: 'TRK-2024-010',
    shippingSession: 'SS-20240721-J',
    customerName: 'PT. Vale Indonesia',
    itemName: 'Generator Set 500kVA',
    itemType: 'Alat Berat',
    origin: 'Pelabuhan Y',
    destination: 'Site Tambang F',
    status: 'Pending',
    lastUpdate: '2024-11-07T07:00:00+07:00',
    estimatedArrival: '2024-11-12T08:00:00+07:00',
    createdBy: 'Supervisor Utama',
    currentCheckpoint: 'Mother Vessel',
    totalCheckpoints: 4,
    completedCheckpoints: 0,
    itemCode: 'EQ-GEN-500',
    currentLocation: 'Menunggu jadwal pemuatan dari kapal',
    totalWeight: '9.1 Ton',
    model: 'Diesel Generator 500kVA',
    manufacturer: 'Cummins',
    finalDestination: 'Site Tambang F, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'pending' },
      { id: 'cp2', name: 'Barge Transit', status: 'pending' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '07:00', date: '07 Nov 2024', title: 'Shipping session dibuat', user: 'Supervisor Utama', role: 'Supervisor' }],
  },
  {
    id: '11',
    contractId: 'TRK-2024-011',
    shippingSession: 'SS-20240722-K',
    customerName: 'PT. Freeport Indonesia',
    itemName: 'Compactor Roller 12T',
    itemType: 'Alat Berat',
    origin: 'Tongkang M',
    destination: 'Pelabuhan Z',
    status: 'Delayed',
    lastUpdate: '2024-11-04T13:00:00+07:00',
    estimatedArrival: '2024-11-03T18:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Pelabuhan',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-CMP-12T',
    currentLocation: 'Pelabuhan, delay proses bea cukai',
    totalWeight: '12.4 Ton',
    model: 'Vibratory Roller 12 Ton',
    manufacturer: 'Sakai',
    finalDestination: 'Site Tambang G, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '30 Okt 2024', time: '06:00', pic: 'Bayu' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '31 Okt 2024', time: '12:00', pic: 'Firman' },
      { id: 'cp3', name: 'Port Handling', status: 'current', date: '04 Nov 2024', time: '13:00', pic: 'Galih', notes: 'Delay proses bea cukai' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '13:00', date: '04 Nov 2024', title: 'Delay dilaporkan - bea cukai', user: 'Galih', role: 'Staff' }],
  },
  {
    id: '12',
    contractId: 'TRK-2024-012',
    shippingSession: 'SS-20240723-L',
    customerName: 'PT. Aneka Tambang',
    itemName: 'Forklift Diesel 5T',
    itemType: 'Alat Berat',
    origin: 'Kapal N',
    destination: 'Tongkang O',
    status: 'In Transit',
    lastUpdate: '2024-11-05T15:20:00+07:00',
    estimatedArrival: '2024-11-08T09:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Tongkang',
    totalCheckpoints: 4,
    completedCheckpoints: 2,
    itemCode: 'EQ-FRK-5T',
    currentLocation: 'Tongkang, menunggu proses lanjutan',
    totalWeight: '5.6 Ton',
    model: 'Diesel Forklift 5 Ton',
    manufacturer: 'Toyota',
    finalDestination: 'Gudang Site H, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '03 Nov 2024', time: '08:00', pic: 'Reza' },
      { id: 'cp2', name: 'Barge Transit', status: 'current', date: '05 Nov 2024', time: '15:20', pic: 'Anton' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '15:20', date: '05 Nov 2024', title: 'Cargo transit via Barge', user: 'Anton', role: 'Staff' }],
  },
  {
    id: '13',
    contractId: 'TRK-2024-013',
    shippingSession: 'SS-20240724-M',
    customerName: 'PT. Harum Energy',
    itemName: 'Tower Light Set',
    itemType: 'Peralatan Pendukung',
    origin: 'Pelabuhan P',
    destination: 'Site Tambang I',
    status: 'Delivered',
    lastUpdate: '2024-11-03T11:00:00+07:00',
    estimatedArrival: '2024-11-03T11:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Site',
    totalCheckpoints: 4,
    completedCheckpoints: 4,
    itemCode: 'EQ-TWL-013',
    currentLocation: 'Terpasang di area kerja',
    totalWeight: '1.2 Ton',
    model: 'Mobile Tower Light',
    manufacturer: 'Wacker Neuson',
    finalDestination: 'Site Tambang I, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'completed', date: '01 Nov 2024', time: '07:00', pic: 'Dimas' },
      { id: 'cp2', name: 'Barge Transit', status: 'completed', date: '01 Nov 2024', time: '16:00', pic: 'Fajar' },
      { id: 'cp3', name: 'Port Handling', status: 'completed', date: '02 Nov 2024', time: '10:00', pic: 'Rian' },
      { id: 'cp4', name: 'Site Delivery', status: 'completed', date: '03 Nov 2024', time: '11:00', pic: 'Sandi' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '11:00', date: '03 Nov 2024', title: 'Cargo arrived at destination', user: 'Sandi', role: 'Staff' }],
  },
  {
    id: '14',
    contractId: 'TRK-2024-014',
    shippingSession: 'SS-20240725-N',
    customerName: 'PT. Medco Energi',
    itemName: 'Water Pump Skid',
    itemType: 'Peralatan Pendukung',
    origin: 'Tongkang Q',
    destination: 'Pelabuhan R',
    status: 'Pending',
    lastUpdate: '2024-11-07T06:30:00+07:00',
    estimatedArrival: '2024-11-11T09:00:00+07:00',
    createdBy: 'Supervisor Utama',
    currentCheckpoint: 'Mother Vessel',
    totalCheckpoints: 4,
    completedCheckpoints: 0,
    itemCode: 'EQ-WPS-014',
    currentLocation: 'Menunggu jadwal pemuatan dari kapal',
    totalWeight: '3.4 Ton',
    model: 'Skid Mounted Pump Unit',
    manufacturer: 'Grundfos',
    finalDestination: 'Site Tambang J, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'pending' },
      { id: 'cp2', name: 'Barge Transit', status: 'pending' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '06:30', date: '07 Nov 2024', title: 'Shipping session dibuat', user: 'Supervisor Utama', role: 'Supervisor' }],
  },
  {
    id: '15',
    contractId: 'TRK-2024-015',
    shippingSession: 'SS-20240726-O',
    customerName: 'PT. Indika Energy',
    itemName: 'Fuel Tank Trailer 20K',
    itemType: 'Alat Berat',
    origin: 'Kapal S',
    destination: 'Tongkang T',
    status: 'Cancelled',
    lastUpdate: '2024-11-02T14:00:00+07:00',
    estimatedArrival: '2024-11-05T10:00:00+07:00',
    createdBy: 'Administrator',
    currentCheckpoint: 'Mother Vessel',
    totalCheckpoints: 4,
    completedCheckpoints: 0,
    itemCode: 'EQ-FTT-20K',
    currentLocation: '-',
    totalWeight: '20 Ton',
    model: 'Fuel Tank Trailer',
    manufacturer: 'Doosung',
    finalDestination: 'Site Tambang K, Kalimantan',
    checkpoints: [
      { id: 'cp1', name: 'Vessel Loading', status: 'pending' },
      { id: 'cp2', name: 'Barge Transit', status: 'pending' },
      { id: 'cp3', name: 'Port Handling', status: 'pending' },
      { id: 'cp4', name: 'Site Delivery', status: 'pending' },
    ],
    documents: [], reports: [], photos: [],
    activities: [{ id: 'act1', time: '14:00', date: '02 Nov 2024', title: 'Shipping session dibatalkan oleh customer', user: 'Administrator', role: 'Admin' }],
  },
];